apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: kind
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: kubernetes
    registry: ghcr.io
  environments:
  - key: dev
    owner: avinashnadendla
    repository: jenkins-x
  - key: staging
  ingress:
    domain: "192.168.40.177"
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: .jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: avinashnadendla
  repository: bucketrepo
  secretStorage: vault
  vault:
    url: http://lenovo-thinkpad-l14-gen-2:8200
  webhook: lighthouse
